### Application
application:
  name: "^project.artifactId^"
  version: "^project.version^"
  timestamp: "^timestamp^"

### Server / API
server:
  port: 9020
  error:
    include-message: always

open-api:
  title: Service Management
  description: REST API of Service Management
  version: "^project.version^"
  contact:
    name: Fraunhofer IPA
    url: https://www.ipa.fraunhofer.de
    email: matthias.schneider@ipa.fraunhofer.de

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    tags-sorter: alpha
    operations-sorter: alpha
    oauth:
      clientId: self-service-portal
      clientSecret: unused-and-not-required

### Database
database:
  host: {{ target_host }}
  port: 3320
  schema: {{ service_management_database_schema }}
  username: {{ service_management_database_user }}
  password: {{ service_management_database_password }}

### Spring
spring:
  application:
    name: service_management
  main:
    allow-bean-definition-overriding: true
  cloud:
    consul:
      host: ${consul.host}
      port: ${consul.port}
      discovery:
        ip-address: {{ local_host | default("172.17.0.1") }}
        acl-token: ${consul.acl-token}
        prefer-ip-address: true
        register-health-check: true
  security:
    user:
      name: "user"
      password: "password"
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name=org: 'mariadb.jdbc.Driver'
    url: jdbc:mariadb://${database.host}:${database.port}/${database.schema}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${database.username}
    password: ${database.password}
  sql:
    init:
      mode: always
      platform: mysql

management:
  endpoints:
    web.exposure.include: health,info
  info:
    git.enabled: false

### Git
git:
  service-offering-importer:
    clone-directory: tmp/
    updater-interval-minutes: 15

### Components - Internal
notification-service:
  scheme: "http"
  host: {{ target_host }}
  port: 9001

resource-management:
  url: "http://{{ target_host }}:9010"

### Keycloak
keycloak:
  config:
    auth-white-list:
    tenants:
      config-path: keycloak/
      client-registration-enable: false
      client-update-enable: false
      resolve-by-path: true
      resolve-by-header: true
      resolver-base-path: /
      resolver-header: Realm
      redirect-uris:
      web-origins:

### AWX
awx:
  scheme: {{ awx_scheme }}
  host: {{ awx_hostname }}
  port: {{ awx_port }}
  username: {{ awx_service_management_username }}
  password: {{ awx_service_management_password }}
  polling-interval-in-s: 4

### Consul
consul:
  scheme: {{ consul_scheme }}
  host: {{ consul_hostname }}
  port: {{ consul_port }}
  datacenter: fabos
  acl-token: {{ consul_service_management_token }}

### Vault
vault:
  scheme: {{ vault_scheme }}
  host: {{ vault_hostname }}
  port: {{ vault_port }}
  authentication: APPROLE
  app-role:
    role-id: {{ vault_service_management_app_role_id }}
    secret-id: {{ vault_service_management_app_secret_id }}
    app-role-path: approle

### BaSyx
basyx:
  aas-registry:
    url: http://{{ target_host }}:4000/registry
  aas-server:
    url: http://{{ target_host }}:4001/aasServer

service-management:
  url: {{ service_management_scheme }}://{{ target_host }}:{{ service_management_port }}
