---
- name: Install docker on target host
  hosts: target
  become: yes
  gather_facts: yes
  tasks:
    - name: include docker role
      ansible.builtin.include_role:
        name: docker

    - name: Copy compose directory
      ansible.builtin.copy:
        src: ../compose
        dest: /tmp/

    - name: Set slm hostname
      ansible.builtin.lineinfile:
        path: /tmp/compose/.env
        regexp: '^SLM_HOSTNAME='
        line: SLM_HOSTNAME=slm

    - name: docker-compose up
      community.docker.docker_compose:
        state: "present"
        project_src: /tmp/compose
      register: docker_compose
      retries: 5
      delay: 5
      until: docker_compose.failed == false





