### Application
application:
  name: "^project.artifactId^"
  version: "^project.version^"
  timestamp: "^timestamp^"

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  application:
    name: resource_management_init
  cloud:
    consul:
      enabled: false
      host: ${consul.host}
      port: ${consul.port}
      discovery:
        acl-token: ${consul.acl-token}
        register: false

resource-management:
  url: http://localhost:9010
  init-directories: init/

keycloak:
  auth-server-url: http://localhost:7080/auth
  realm: fabos
  username: fabos
  password: password

### Consul
consul:
  scheme: http
  host: localhost
  port: 8500
  datacenter: fabos
  acl-token: fBQjSo6nGOjiIDA5ZewZYZz4

