### Application
application:
  name: "^project.artifactId^"
  version: "^project.version^"
  timestamp: "^timestamp^"

### Server / API
server:
  port: 9001
  error:
    include-message: always

open-api:
  title: Notification Service
  description: REST API of Notification Service
  version: "^project.version^"
  contact:
    name: Fraunhofer IPA
    url: https://www.ipa.fraunhofer.de
    email: matthias.schneider@ipa.fraunhofer.de

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    tags-sorter: alpha
    operations-sorter: alpha
    oauth:
      clientId: self-service-portal
      clientSecret: unused-and-not-required

### Database
database:
  host: {{ target_host }}
  port: 3301
  schema: {{ notification_service_database_schema }}
  username: {{ notification_service_database_user }}
  password: {{ notification_service_database_password }}

### Spring
spring:
  application:
    name: notification_service
  security:
    user:
      name: admin
      password: password
  cloud:
    consul:
      host: ${consul.host}
      port: ${consul.port}
      discovery:
        ip-address: {{ local_host | default("172.17.0.1") }}
        acl-token: ${consul.acl-token}
        prefer-ip-address: true
        register-health-check: true
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    initialization-mode: always
    driver-class-name=org: 'mariadb.jdbc.Driver'
    url: jdbc:mariadb://${database.host}:${database.port}/${database.schema}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${database.username}
    password: ${database.password}

management:
  endpoints:
    web.exposure.include: health,info
  info:
    git.enabled: false

### Components - Internal
notification-service:
  scheme: "http"
  host: {{ target_host }}
  port: ${server.port}

### Keycloak
keycloak:
  config:
    auth-white-list:
    tenants:
      config-path: keycloak/
      client-registration-enable: false
      client-update-enable: false
      resolve-by-path: true
      resolve-by-header: true
      resolver-base-path: /
      resolver-header: Realm
      redirect-uris:
      web-origins:

### AWX
awx:
  scheme: {{ awx_scheme }}
  host: {{ awx_hostname }}
  port: {{ awx_port }}
  username: {{ awx_notification_service_username }}
  password: {{ awx_notification_service_password }}
  polling-interval-in-s: 4

### Consul
consul:
  scheme: {{ consul_scheme }}
  host: {{ consul_hostname }}
  port: {{ consul_port }}
  datacenter: fabos
  acl-token: {{ consul_resource_management_token }}
