version: '3'

services:

  catalog:
    image: ghcr.io/eclipse-slm/slm/catalog:${SLM_CATALOG_VERSION}
    restart: unless-stopped
    depends_on:
      - catalog-database
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    environment:
      SPRING_CLOUD_CONSUL_DISCOVERY_IPADDRESS: "${SLM_IP}"
    ports:
      - "${SLM_CATALOG_SERVICE_PORT}:10000"
    networks:
      default:
        aliases:
          - catalog
    extra_hosts:
      - "${SLM_HOSTNAME}:172.17.0.1"
    volumes:
      - catalog-database_config:/app/database/config
      - consul_config_catalog:/app/consul:ro
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:10000/swagger-ui/index.html" ]

  catalog-database:
    image: ghcr.io/eclipse-slm/mariadb:${SLM_CATALOG_SERVICE_DATABASE_VERSION}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: ${LOGGING_MAX_FILE}
        max-size: ${LOGGING_MAX_SIZE}
    ports:
      - "${SLM_CATALOG_SERVICE_DATABASE_PORT}:3306"
    networks:
      default:
        aliases:
          - catalog-database
    environment:
      MYSQL_USER: catalog
      MYSQL_DATABASE: catalog
    volumes:
      - catalog-database_data:/var/lib/mysql
      - catalog-database_config:/config
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]

networks:
  default:

volumes:
  catalog-database_data:
  catalog-database_config:
