version: '3'

services:
  remote-config-exporter:
    image: remote-config-exporter
    build: .
    volumes:
      - "..:/opt/playbooks"
      - "../../../:/project"
      - "../../src/config-exporter/templates:/templates"
    environment:
      ANSIBLE_HOST: "${ANSIBLE_HOST}"
      ANSIBLE_USER: "${ANSIBLE_USER}"
      ANSIBLE_PASSWORD: "${ANSIBLE_PASSWORD}"
      PROJECT_FOLDER: "${PROJECT_FOLDER}"
      LOCAL_HOST: "${LOCAL_HOST}"