---
target:
  hosts:
#    target_ssh_host:
#      ansible_host: "{{ lookup('env', 'ANSIBLE_HOST') }}"
#      ansible_user: "{{ lookup('env', 'ANSIBLE_USER') }}"
#      ansible_password: "{{ lookup('env', 'ANSIBLE_PASSWORD') }}"
#      ansible_ssh_common_args: '-o StrictHostKeyChecking\=no -o ServerAliveInterval=10'
    target_win_ssh_host:
      ansible_host: "{{ lookup('env', 'ANSIBLE_HOST') }}"
      ansible_user: "{{ lookup('env', 'ANSIBLE_USER') }}"
      ansible_password: "{{ lookup('env', 'ANSIBLE_PASSWORD') }}"
      ansible_ssh_common_args: '-o StrictHostKeyChecking\=no -o ServerAliveInterval=10'
      ansible_shell_type: "cmd"
      ansible_become_user: "{{ lookup('env', 'ANSIBLE_USER') }}"
      ansible_become_pass: "{{ lookup('env', 'ANSIBLE_PASSWORD') }}"
      ansible_become_method: "runas"
